### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by DanBmh** [german-asr/megs#4]
I like the idea of a greater corpus with predefined train/test splittings, but i have some questions:

1. How did you do the split? Some datasets like CV and Tuda already provide splits, did you use them or did you split everything randomly?

2. How did you normalize the transcriptions? What did you do with special characters, umlauts and numbers?
Currently I'm replacing everything except a-z for easier transfer learning with English (but umlaut replacing a->ae, ... also improved the accuracy without transfer learning). 

3. It seems you did exclude almost 40% of the datasets, are there reasons other than >25s length?
In my trainings I'm also excluding files by length (>45s and <1s) and by larger differences in chars/sec speaking rate compared to the average, but in summary I'm excluding only about 2-3%.

My preprocessing code is [here](https://github.com/DanBmh/deepspeech-german/blob/master/preprocessing/dataset_operations.py)

**Comment by ynop** [comment]
1. Per original dataset: If there were existing splits, I kept them. Otherwise I use 15% for dev and 15% for test (but max. 15000s to keep the test/dev relatively small, otherwise for SWC you would have like a 40h test set). Finally I merged all splits of the datasets (e.g. test-cv, test-tuda, ... -> test).

2. You can find all the rules here https://github.com/ynop/spoteno/blob/master/spoteno/configuration/de.py. I also include umlauts, but replaced everything else (thats not a-z, ä, ü, ö) like numbers, symbols, abbreviations, as far as possible.

3. Apart from the validations, I left out a lot from tuda, because there are 4-5 times the same utterances just recorded simultaneously with different microphones. Then the CV dataset does ignore a lot of hours in the train/test/dev sets. As far as I know they only include a single occurrence of every sentence.

**Comment by DanBmh** [comment]
Thanks for your answer.

1. Did you check for the same transcriptions occurring in train/test set? In CV there are some as far as I remember (but it didn't have an impact on my testing results)

3. Isn't it possible to use everything from CV not in dev/test set in the train set?

**Comment by ynop** [comment]
1. No, I just made sure that one speaker only appears in one of the splits.

2. Yes, I think they have a split called `validated` or something. You could just remove any test/dev utterances from there and use it as train. But I am not sure how many repetitions of a single sentence there are. Might have an impact on the test results.

**Comment by DanBmh** [comment]
Last questions for now:

1. Can I use the the scripts with already preprocessed data? I did use audiomate to download and save it in DeepSpeech format. So some the audiofiles are distributed into two directories, original and prepared (converted to wav). 

2. The scripts don't affect other datasets, so I have to normalize and add them to the trainset manually?

**Comment by ynop** [comment]
I don't understand what you are trying to do.
But in general, I think it doesn't matter if the data is already preprocessed, as long as you can load it in audiomate.

**Comment by DanBmh** [comment]
I already have the datasets, but the audiofiles are distributed into two directories because some of them were converted to wav.
For example the audio from Voxforge is in `data_original/voxforge/audio/` because it already is in wav format, but the data of CV is in `data_prepared/cv/audio/`. I did export it with audiomate (with random splits), but i'm not sure i can load it again.
So I need a way where I can generate and use your megs split instead of my splits, without converting and preferably without moving the files.

**Comment by ynop** [comment]
I don't think so, since the scripts for megs rely on the original datasets. Wouldn't it be easier to download them again?

**Comment by DanBmh** [comment]
The problem is more the conversion, this did take over 20h, I would prefer if I dont have to do this again. I still have all the original files, but I also need a mapping between the original paths and the converteds path of the audio files.
